name: CI
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
            cd /apps/artificial_human_bot/
            git pull
            source /apps/artificial_human_bot/.venv/bin/activate
            pip install -r requirements.txt
            systemctl restart artificial_human_bot
